### PR TITLE
fix for patch 10.1.5 (see #209)

### LINKED ISSUE #209: LUA error in 10.1.5
**Running Software (issues missing this information will be deleted):**
 - Addon version:10.1
 - Server patch: 50401

 **Have you read the changelog? (please don't waste our time)**
 Yes.

**Describe the bug**
Right click on repair vendor, auto repairs and generates the LUA error.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to repair vendor
2. Right click on repair vendor to auto repair items.

**Expected behaviour**
Expect no LUA error to appear.

**Screenshots**
N/A

**Error Logs**
18x Scrap/addons/merchant/button.lua:166: attempt to index global 'MerchantRepairText' (a nil value)
[string "@Scrap/addons/merchant/button.lua"]:166: in function `UpdatePosition'
[string "@Scrap/addons/merchant/button.lua"]:74: in function `?'
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:109: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:109>
[string "=[C]"]: ?
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `SendMessage'
[string "@BagBrother/libs/WildAddon-1.0-1/WildAddon-1.0.lua"]:83: in function `SendSignal'
[string "@Scrap/addons/main/main.lua"]:47: in function <Scrap/addons/main/main.lua:47>
[string "=[C]"]: ?
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:19: in function <...Ons/Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:15>
[string "@Ace3/CallbackHandler-1.0-8/CallbackHandler-1.0.lua"]:54: in function `Fire'
[string "@Ace3/AceEvent-3.0-4/AceEvent-3.0.lua"]:120: in function <Ace3/AceEvent-3.0/AceEvent-3.0.lua:119>

Locals:
self = Button {
 0 = <userdata>
 OnEnter = <function> defined @Scrap/addons/merchant/button.lua:129
 UnregisterAllEvents = <function> defined @Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 OnReceiveDrag = <function> defined @Scrap/addons/merchant/button.lua:121
 Delaying = <function> defined @BagBrother/libs/MutexDelay-1.0/MutexDelay-1.0.lua:46
 UpdateState = <function> defined @Scrap/addons/merchant/button.lua:143
 OnMerchant = <function> defined @Scrap/addons/merchant/button.lua:59
 UpdatePosition = <function> defined @Scrap/addons/merchant/button.lua:149
 OnClose = <function> defined @Scrap/addons/merchant/button.lua:86
 Sell = <function> defined @Scrap/addons/merchant/button.lua:191
 Delay = <function> defined @BagBrother/libs/MutexDelay-1.0/MutexDelay-1.0.lua:27
 Tag = "SCRAP_"
 OnBagUpdate = <function> defined @Scrap/addons/merchant/button.lua:78
 AnyJunk = <function> defined @Scrap/addons/merchant/button.lua:238
 RegisterMessage = <function> defined @Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
 UnregisterMessage = <function> defined @Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 border = Texture {
 }
 GetReport = <function> defined @Scrap/addons/merchant/button.lua:223
 UpdateTip = <function> defined @Scrap/addons/merchant/button.lua:169
 SendMessage = <function> defined @Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:49
 CanGuildRepair = <function> defined @Scrap/addons/merchant/button.lua:253
 UnregisterSignal = <function> defined @BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:78
 RegisterSignal = <function> defined @BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:74
 UnregisterAllMessages = <function> defined @Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:164
 background = Texture {
 }
 icon = Texture {
 }
 SendSignal = <function> defined @BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:82
 OnEnable = <function> defined @Scrap/addons/merchant/button.lua:25
 OnLeave = <function> defined @Scrap/addons/merchant/button.lua:134
 NewModule = <function> defined @BagBrother/libs/WildAddon-1.0/WildAddon-1.0.lua:68
 Repair = <function> defined @Scrap/addons/merchant/button.lua:242
 OnClick = <function> defined @Scrap/addons/merchant/button.lua:94
 UnregisterEvent = <function> defined @Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:143
 RegisterEvent = <function> defined @Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:80
}
(*temporary) = nil
(*temporary) = nil
(*temporary) = 1.100000
(*temporary) = <userdata>
(*temporary) = "LEFT"
(*temporary) = -17
(*temporary) = 0.500000
(*temporary) = <userdata>
(*temporary) = nil
(*temporary) = "attempt to index global 'MerchantRepairText' (a nil value)"

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by SeemannJenkins**
- fixed #209
- also realigned the scrap button in the ui to avoid clipping and to match the default blizzard one

hope this helps and thank you for your work!

### CODE REVIEW

**Comment by GurliGebis** [comment]
Well, since the license of this addon has been changed to All Rights Reserved, technically, you cannot legally make changes to it.
So unless we can get a specific permission to make changes and publish them, it would be illegal to do so (even providing fixes), since it breaks the copyright law. (No, I am not a fan of it at all, but since @Jaliborc previously tried to pass his addons off a GPL-3, while preventing people from having the rights that license provides, I wouldn't be surprised, if he acts poorly to people having forks of his addon, even to provide fixes) 😟

**Comment by GurliGebis** [comment]
@SeemannJenkins you can see this commit he did a while ago: https://github.com/Jaliborc/Scrap/commit/9c95d9708106cebc11c3856965f78a54aec88c34

He went from GPL-3 (with all of your rights removed, which is a big joke) to a closed source license.

I don't think we will hear from him, unless he starts to lose Patreon subscribers to it 😟

**Comment by pattyland** [comment]
It hate doing this is PR Dicussion but it seems fitting: https://discord.com/channels/1044414761573564466/1044414762840240204/1126580170250264659

**Review by karpana — APPROVED** [review]
nothing untoward in these changes.  Should be good to go commit the PR to the mainline.  Definitely appreciate the tidy-up in the code.

**Pull request closed without merging**
