### PR TITLE
Changes needed for 10.0.2 compatibility

### PR DESCRIPTION
**Pull request by GurliGebis**
This is the changes needed for 10.0.2 compatibility

### CODE REVIEW

**Comment by shamsup** [comment]
This patch worked for me, thanks!

**Comment by symmetriq** [comment]
Works for me too. Cheers!

**Review by JackTrapper — APPROVED** [review]

**Review by JackTrapper — APPROVED** [review]

**Comment by aurel-burik** [comment]
Works, but I get this error every time I sell something manually. Would it be possible to adjust a little to no longer throw a lua error?

```
13x Interface/AddOns/Scrap/addons/merchant/learning.lua:80: attempt to perform arithmetic on local 'stack' (a nil value)
[string "@Interface/AddOns/Scrap/addons/merchant/learning.lua"]:80: in function `GetDecay'
[string "@Interface/AddOns/Scrap/addons/merchant/learning.lua"]:43: in function `OnItemSold'
[string "@Interface/AddOns/Scrap/addons/merchant/learning.lua"]:27: in function <Interface/AddOns/Scrap/addons/merchant/learning.lua:25>
[string "=[C]"]: in function `UseContainerItem'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1409: in function `ContainerFrameItemButton_OnClick'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1461: in function <Interface/FrameXML/ContainerFrame.lua:1448>

Locals:
self = <table> {
 SendSignal = <function> defined @Interface/AddOns/Scrap/libs/WildAddon-1.0/WildAddon-1.0.lua:82
 RegisterMessage = <function> defined @Interface/AddOns/AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Interface/AddOns/AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:153
 SendMessage = <function> defined @Interface/AddOns/AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:59
 UnregisterSignal = <function> defined @Interface/AddOns/Scrap/libs/WildAddon-1.0/WildAddon-1.0.lua:78
 GetDecay = <function> defined @Interface/AddOns/Scrap/addons/merchant/learning.lua:78
 RegisterEvent = <function> defined @Interface/AddOns/AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 UnregisterAllMessages = <function> defined @Interface/AddOns/AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:174
 IsActive = <function> defined @Interface/AddOns/Scrap/addons/merchant/learning.lua:74
 OnItemSold = <function> defined @Interface/AddOns/Scrap/addons/merchant/learning.lua:40
 OnEnable = <function> defined @Interface/AddOns/Scrap/addons/merchant/learning.lua:24
 UnregisterAllEvents = <function> defined @Interface/AddOns/AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:174
 OnItemRefund = <function> defined @Interface/AddOns/Scrap/addons/merchant/learning.lua:55
 RegisterSignal = <function> defined @Interface/AddOns/Scrap/libs/WildAddon-1.0/WildAddon-1.0.lua:74
 NewModule = <function> defined @Interface/AddOns/Scrap/libs/WildAddon-1.0/WildAddon-1.0.lua:68
 UnregisterEvent = <function> defined @Interface/AddOns/AllTheThings/lib/CallbackHandler-1.0/CallbackHandler-1.0.lua:153
 Tag = "SCRAP_"
}
id = 173835
stack = nil
maxStack = 1
(*temporary) = 8
(*temporary) = "Malignant Leviathan's Pauldrons"
(*temporary) = "|cff0070dd|Hitem:173835::::::::60:72:::::::::|h[Malignant Leviathan's Pauldrons]|h|r"
(*temporary) = "attempt to perform arithmetic on local 'stack' (a nil value)"

```

**Comment by GurliGebis** [comment]
I think something else is causing it to fail.
I just tested it, and it works fine - but the problem is some other addon can cause issues, that breaks this addon (and all other addon)

**Comment by aurel-burik** [comment]
I tested it again with only Scrap, Scrap Merchant and Scrap Options  addons enabled. The issue is still present.
1. Find item in bags that is NOT on the autosell list.
2. Sell it to vendor (transaction is successful, but:)
--> Error pops out
```
Message: Interface/AddOns/Scrap/addons/merchant/learning.lua:80: attempt to perform arithmetic on local 'stack' (a nil value)
Time: Sat Nov 19 15:02:30 2022
Count: 1
Stack: Interface/AddOns/Scrap/addons/merchant/learning.lua:80: attempt to perform arithmetic on local 'stack' (a nil value)
[string "@Interface/AddOns/Scrap/addons/merchant/learning.lua"]:80: in function `GetDecay'
[string "@Interface/AddOns/Scrap/addons/merchant/learning.lua"]:43: in function `OnItemSold'
[string "@Interface/AddOns/Scrap/addons/merchant/learning.lua"]:27: in function <Interface/AddOns/Scrap/addons/merchant/learning.lua:25>
[string "=[C]"]: in function `UseContainerItem'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1409: in function `ContainerFrameItemButton_OnClick'
[string "@Interface/FrameXML/ContainerFrame.lua"]:1461: in function <Interface/FrameXML/ContainerFrame.lua:1448>

Locals: self = <table> {
 SendSignal = <function> defined @Interface/AddOns/Scrap/libs/WildAddon-1.0/WildAddon-1.0.lua:82
 RegisterMessage = <function> defined @Interface/AddOns/Scrap/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 UnregisterMessage = <function> defined @Interface/AddOns/Scrap/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:153
 SendMessage = <function> defined @Interface/AddOns/Scrap/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:59
 UnregisterSignal = <function> defined @Interface/AddOns/Scrap/libs/WildAddon-1.0/WildAddon-1.0.lua:78
 GetDecay = <function> defined @Interface/AddOns/Scrap/addons/merchant/learning.lua:78
 RegisterEvent = <function> defined @Interface/AddOns/Scrap/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 UnregisterAllMessages = <function> defined @Interface/AddOns/Scrap/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:174
 IsActive = <function> defined @Interface/AddOns/Scrap/addons/merchant/learning.lua:74
 OnItemSold = <function> defined @Interface/AddOns/Scrap/addons/merchant/learning.lua:40
 OnEnable = <function> defined @Interface/AddOns/Scrap/addons/merchant/learning.lua:24
 UnregisterAllEvents = <function> defined @Interface/AddOns/Scrap/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:174
 OnItemRefund = <function> defined @Interface/AddOns/Scrap/addons/merchant/learning.lua:55
 RegisterSignal = <function> defined @Interface/AddOns/Scrap/libs/WildAddon-1.0/WildAddon-1.0.lua:74
 NewModule = <function> defined @Interface/AddOns/Scrap/libs/WildAddon-1.0/WildAddon-1.0.lua:68
 UnregisterEvent = <function> defined @Interface/AddOns/Scrap/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:153
 Tag = "SCRAP_"
}
id = 14047
stack = nil
maxStack = 1000
(*temporary) = 8
(*temporary) = "Runecloth"
(*temporary) = "[Runecloth]"
(*temporary) = "attempt to perform arithmetic on local 'stack' (a nil value)"

```

**Comment by GurliGebis** [comment]
> I tested it again with only Scrap, Scrap Merchant and Scrap Options addons enabled. The issue is still present.
> 
>     1. Find item in bags that is NOT on the autosell list.
> 
>     2. Sell it to vendor (transaction is successful, but:)
>        --> Error pops out
> 
> 
> ```
> Message: Interface/AddOns/Scrap/addons/merchant/learning.lua:80: attempt to perform arithmetic on local 'stack' (a nil value)
> Time: Sat Nov 19 15:02:30 2022
> Count: 1
> Stack: Interface/AddOns/Scrap/addons/merchant/learning.lua:80: attempt to perform arithmetic on local 'stack' (a nil value)
> [string "@Interface/AddOns/Scrap/addons/merchant/learning.lua"]:80: in function `GetDecay'
> [string "@Interface/AddOns/Scrap/addons/merchant/learning.lua"]:43: in function `OnItemSold'
> [string "@Interface/AddOns/Scrap/addons/merchant/learning.lua"]:27: in function <Interface/AddOns/Scrap/addons/merchant/learning.lua:25>
> [string "=[C]"]: in function `UseContainerItem'
> [string "@Interface/FrameXML/ContainerFrame.lua"]:1409: in function `ContainerFrameItemButton_OnClick'
> [string "@Interface/FrameXML/ContainerFrame.lua"]:1461: in function <Interface/FrameXML/ContainerFrame.lua:1448>
> 
> Locals: self = <table> {
>  SendSignal = <function> defined @Interface/AddOns/Scrap/libs/WildAddon-1.0/WildAddon-1.0.lua:82
>  RegisterMessage = <function> defined @Interface/AddOns/Scrap/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
>  UnregisterMessage = <function> defined @Interface/AddOns/Scrap/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:153
>  SendMessage = <function> defined @Interface/AddOns/Scrap/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:59
>  UnregisterSignal = <function> defined @Interface/AddOns/Scrap/libs/WildAddon-1.0/WildAddon-1.0.lua:78
>  GetDecay = <function> defined @Interface/AddOns/Scrap/addons/merchant/learning.lua:78
>  RegisterEvent = <function> defined @Interface/AddOns/Scrap/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
>  UnregisterAllMessages = <function> defined @Interface/AddOns/Scrap/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:174
>  IsActive = <function> defined @Interface/AddOns/Scrap/addons/merchant/learning.lua:74
>  OnItemSold = <function> defined @Interface/AddOns/Scrap/addons/merchant/learning.lua:40
>  OnEnable = <function> defined @Interface/AddOns/Scrap/addons/merchant/learning.lua:24
>  UnregisterAllEvents = <function> defined @Interface/AddOns/Scrap/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:174
>  OnItemRefund = <function> defined @Interface/AddOns/Scrap/addons/merchant/learning.lua:55
>  RegisterSignal = <function> defined @Interface/AddOns/Scrap/libs/WildAddon-1.0/WildAddon-1.0.lua:74
>  NewModule = <function> defined @Interface/AddOns/Scrap/libs/WildAddon-1.0/WildAddon-1.0.lua:68
>  UnregisterEvent = <function> defined @Interface/AddOns/Scrap/libs/CallbackHandler-1.0/CallbackHandler-1.0.lua:153
>  Tag = "SCRAP_"
> }
> id = 14047
> stack = nil
> maxStack = 1000
> (*temporary) = 8
> (*temporary) = "Runecloth"
> (*temporary) = "[Runecloth]"
> (*temporary) = "attempt to perform arithmetic on local 'stack' (a nil value)"
> ```

Can you give it a try now and see if it is better.

**Comment by aurel-burik** [comment]
Tested it, works perfect, no more errors 👍 Thank you!

**Comment by GurliGebis** [comment]
@Jaliborc this one should be good to go :)

**Comment by Jaliborc** [comment]
Breaks every other client unfortunately 👎🏻

**Pull request closed without merging**
